### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by monolithed** [vanruesc/blur-up#10]
```
/node_modules/svg-blur-up/dist/blur-up.js: No such file or directory
```
<img width="189" alt="Screenshot 2023-08-30 at 18 25 55" src="https://github.com/vanruesc/blur-up/assets/803674/a37b22c5-a9df-41d6-894a-c96b60e140cb">
<img width="486" alt="Screenshot 2023-08-30 at 18 26 44" src="https://github.com/vanruesc/blur-up/assets/803674/826548ad-e96a-4241-8e43-a1c754dc7d15">

**Comment by vanruesc** [comment]
Thanks for the report!

Should be fixed in `svg-blur-up@3.0.0`.
