### ISSUE TITLE
Feature request: Retain path structure when using wildcard

### ISSUE THREAD

**Issue by robsterlini** [vanruesc/blur-up#3]
Firstly, thank you for making this tool. It's great, and even without this feature, it's very useful.

One issue I've come across (and I spent a bit of time trying different solutions) is that I have a lot of images in different directories (some with clashing names):

```
foo/
  image1.jpg
  image2.jpg
bar/
  image1.jpg
  image2.jpg
```

The tool misreports the number of SVGs generated when the file names clash (here there would only be 2 in the end directory). I was wondering if it would be possible to make it so that it kept the directory names in the output?

Cheers!

**Comment by vanruesc** [comment]
> I was wondering if it would be possible to make it so that it kept the directory names in the output?

Yes, that should be possible. I'll look into it when I get a chance.

**Comment by vanruesc** [comment]
Folder structures will now be preserved in `svg-blur-up@2.0.0`.
